### PR TITLE
Frontend Todo List

### PR DESCRIPTION
**Pull request by NuffSaid-Bore**
I used react for  my frontend and for backend i used node js running on express.

### CODE REVIEW

**Comment by NuffSaid-Bore** [comment]
Greeting team @Sinawo @BAHLEMAJOLA @zolwethu @TshepoMagagula 

I have completed my objectives for the day please review and provide your insight on the project. I look forward to your review.

**Review by zolwethu — CHANGES_REQUESTED** [review]
@NuffSaid-Bore You should follow the instructions to switch to ES Modules by replacing all `require` statements with `import` in your index.js file. There's no need to use `export` in this case, as you're simply setting up a server, but it was included in the instructions.

**Comment by NuffSaid-Bore** [comment]
> @NuffSaid-Bore You should follow the instructions to switch to ES Modules by replacing all `require` statements with `import` in your index.js file. There's no need to use `export` in this case, as you're simply setting up a server, but it was included in the instructions.

@zolwethu thanks for the review however i had already made those changes...please refer to the development brance server folder instead of the man branch server folder to witness the suggested changes.

**Review by TshepoMagagula — CHANGES_REQUESTED** [review]
todoL

@NuffSaid-Bore This is how it looks on a smaller display. Please make it responsive as the Complete and Uncomplete span is not visible.

**Review by TshepoMagagula — CHANGES_REQUESTED** [review]
serverError

@NuffSaid-Bore add details on your README file for the user to add the env file to avoid this error when they run the server.

**Comment by NuffSaid-Bore** [comment]
> todoL
> 
> @NuffSaid-Bore This is how it looks on a smaller display. Please make it responsive as the Complete and Uncomplete span is not visible.

@TshepoMagagula Thanks for the review i just fixed the modal to be responsive for smaller screens please advise if this is correct: here: https://github.com/NuffSaid-Bore/Todo-List/commit/28c759438953cb9ca033ad5d8c3188a14ca28d4f
Screenshot 2024-11-12 093959

**Comment by NuffSaid-Bore** [comment]
> serverError
> 
> @NuffSaid-Bore add details on your README file for the user to add the env file to avoid this error when they run the server.

@TshepoMagagula Thanks for the review i have amended my README file to accommodate for the oversight you can find details here: https://github.com/NuffSaid-Bore/Todo-List/pull/1/commits/00cb4d51b8f84c32641f8b0bba85cd8f5c1d8015

**Pull request closed without merging**
